"""
Research pipeline: 3-round search, synthesis, and persistence.

Pipeline:
  Round 1 -- Broad search on the topic directly
  Round 2 -- Sub-topic searches generated by Minimax from initial results
  Round 3 -- Verification searches for key claims
  Synthesis -- Structured research document with source citations
"""

import re
import json
import logging
import asyncio
import contextvars
import httpx
from datetime import datetime, timezone
from urllib.parse import urlparse

from app.config import (
    SERPER_API_KEY,
    MINIMAX_API_KEY,
    LLM_PROVIDER,
    TIER1_DOMAINS,
    TIER1_SUBSTRINGS,
    TIER2_SUBSTRINGS,
    SYNTHESIS_SYSTEM_PROMPT,
)
from app.llm import llm_chat
from app import db

logger = logging.getLogger("kb-service.research")


# --- Auto-discovery accounting ---------------------------------------------
#
# These ContextVars let _search_serper attribute every call to the correct
# KB + job for per-KB daily budget tracking, without threading parameters
# through every helper in the pipeline.
_current_job_id: contextvars.ContextVar[int | None] = contextvars.ContextVar(
    "current_job_id", default=None,
)
_current_kb: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "current_kb", default=None,
)


# --- Search providers -------------------------------------------------------
#
# Provider implementations live in ``app/sources/``. Round 1 of
# ``run_research`` iterates every registered provider via
# ``_round1_search_all_providers`` (Serper, Tavily, arXiv, HN, Wikipedia,
# plus any newly registered providers). Rounds 2 and 3 stay Serper-only
# because they use targeted LLM-generated queries — ``_search_serper``
# below is the shared entrypoint for those rounds.

async def _search_serper(
    client: httpx.AsyncClient, query: str, num: int = 8
) -> list[dict]:
    """Thin shim over ``app.sources.SerperProvider`` for rounds 2/3."""
    from app.sources import SerperProvider
    return await SerperProvider(client).search(query, num=num)


async def _round1_search_all_providers(
    client: httpx.AsyncClient, query: str, per_provider: int = 5,
) -> list[dict]:
    """Run round 1 against every registered provider in parallel.

    Each provider:
      - returns at most ``per_provider`` results
      - has ~15s to complete via httpx defaults; failures are caught and logged
      - graceful degradation: missing API keys → empty list, no exception

    Returns the merged result list (caller still dedups + tier-scores).
    """
    from app.sources import get_provider_classes

    provider_classes = get_provider_classes()
    if not provider_classes:
        return []

    async def _run_one(provider_cls):
        try:
            provider = provider_cls(client)
            results = await provider.search(query, num=per_provider)
            return (provider_cls.name, results or [])
        except Exception as exc:
            logger.warning(
                "Round 1 provider %s failed: %s", provider_cls.name, exc,
            )
            return (provider_cls.name, [])

    pairs = await asyncio.gather(*[_run_one(p) for p in provider_classes])
    merged: list[dict] = []
    for name, results in pairs:
        if results:
            logger.info("Round 1 [%s]: %d results", name, len(results))
            merged.extend(results)
    return merged


# --- LLM helper (delegates to app.llm) ------------------------------------

async def _chat(
    client: httpx.AsyncClient,
    system_msg: str,
    user_msg: str,
    max_tokens: int = 4000,
    temperature: float = 0.2,
    *,
    model: str | None = None,
    provider: str | None = None,
) -> str:
    """Send a chat completion via the configured LLM provider.

    Optional ``model`` and ``provider`` kwargs override the global default
    for a single call. Used to route synthesis through the per-KB
    ``kb_settings.synthesis_provider`` / ``synthesis_model``.
    """
    return await llm_chat(
        system_msg, user_msg, max_tokens, temperature,
        client=client, model=model, provider=provider,
    )


# --- Sub-question / verification generators ---------------------------------

async def _generate_sub_questions(
    client: httpx.AsyncClient, topic: str, round1_summaries: str
) -> list[str]:
    """Generate follow-up research sub-questions using chain-of-thought evaluation."""
    prompt = (
        f'You are evaluating search results about "{topic}" to decide what to research next.\n\n'
        f"Step 1 - EVALUATE what you have: Review the sources below. Think about:\n"
        f"  - What aspects of this topic are well-covered by authoritative sources?\n"
        f"  - What aspects are missing, vague, or only covered by low-quality sources?\n"
        f"  - Are there obvious follow-up questions a reader would have?\n\n"
        f"Step 2 - DECIDE what's needed: Based on your evaluation, generate 3-4 specific "
        f"sub-questions that would fill the most important gaps. Focus on:\n"
        f"- Aspects no source covered well (biggest gaps first)\n"
        f"- Practical details that are vague or missing\n"
        f"- Comparisons or alternatives readers would want to know\n"
        f"- Recent developments the initial search may have missed\n\n"
        f"Return ONLY the questions, one per line, no numbering or bullets. "
        f"Put the most important gap first.\n\n"
        f"Initial results:\n{round1_summaries}"
    )
    response = await _chat(
        client,
        system_msg="You are a research agent evaluating source coverage. Think step by step about what's missing, then generate targeted sub-questions to fill the biggest gaps. Return only the questions, one per line.",
        user_msg=prompt,
        max_tokens=600,
        temperature=0.3,
    )
    return [
        q.strip().lstrip("0123456789.-) ")
        for q in response.strip().split("\n")
        if q.strip() and len(q.strip()) > 10
    ][:4]


async def _generate_verification_queries(
    client: httpx.AsyncClient, topic: str, sources_text: str
) -> list[str]:
    """Identify claims needing verification using chain-of-thought reasoning."""
    prompt = (
        f'You are fact-checking research about "{topic}" before it gets published.\n\n'
        f"Step 1 - SCAN for risky claims: Review the sources and identify claims that:\n"
        f"  - Are only supported by a single source (especially Tier 3)\n"
        f"  - Contain specific numbers, versions, prices, or dates that could be outdated\n"
        f"  - Make strong comparative claims (faster, better, replaces X)\n"
        f"  - Contradict another source in the results\n"
        f"  - Would be embarrassing to publish if wrong\n\n"
        f"Step 2 - PRIORITIZE: Pick the 2-3 claims that matter most to get right. "
        f"A wrong version number in a recommendation is worse than a wrong founding date.\n\n"
        f"Step 3 - Generate a targeted search query for each claim that would find "
        f"an independent source to confirm or deny it.\n\n"
        f"Return ONLY the search queries, one per line.\n\n{sources_text}"
    )
    response = await _chat(
        client,
        system_msg="You are a fact-checker. Think step by step: scan for risky claims, prioritize the ones that matter most, then generate verification queries. Return only search queries, one per line.",
        user_msg=prompt,
        max_tokens=500,
        temperature=0.2,
    )
    return [
        q.strip().lstrip("0123456789.-) ")
        for q in response.strip().split("\n")
        if q.strip() and len(q.strip()) > 10
    ][:3]


# --- Source scoring & dedup -------------------------------------------------

def _score_source_tier(url: str) -> int:
    """Score a URL's authority tier. Returns 1 (highest), 2, or 3 (lowest)."""
    if not url:
        return 3
    url_lower = url.lower()

    try:
        hostname = urlparse(url_lower).hostname or ""
    except Exception:
        hostname = ""

    tld = hostname.rsplit(".", 1)[-1] if "." in hostname else ""
    if tld in TIER1_DOMAINS:
        return 1

    for pattern in TIER1_SUBSTRINGS:
        if pattern in url_lower:
            return 1
    for pattern in TIER2_SUBSTRINGS:
        if pattern in url_lower:
            return 2

    return 3


def _tier_label(tier: int) -> str:
    return {1: "Tier 1 - Authoritative", 2: "Tier 2 - Reputable", 3: "Tier 3 - General"}[tier]


# Self-citation lint — strip ``[label](url)`` links whose URL was never in
# the source set the model was given. The regex catches every inline link
# and ignores reference-style links + bare URLs in code fences.
_MARKDOWN_LINK_RE = re.compile(r"\[([^\]]+)\]\((https?://[^)\s]+)\)")


def _normalize_url_for_match(url: str) -> str:
    """Strip protocol + trailing slash + leading www. for fuzzy URL matching."""
    if not url:
        return ""
    u = url.strip().rstrip("/").lower()
    u = u.replace("https://", "").replace("http://", "")
    if u.startswith("www."):
        u = u[4:]
    return u


def _lint_citations(
    markdown: str, source_urls: list[str],
) -> tuple[str, list[str]]:
    """Strip hallucinated citation links from synthesis output.

    Walks every ``[label](url)`` in *markdown*. Any URL not present in the
    *source_urls* set (matched after protocol/www normalization) gets its
    link stripped — the label text is preserved so the prose still reads
    naturally, just without the fake link. Returns the cleaned markdown
    plus the list of stripped URLs (for logging onto the job record).
    """
    if not markdown:
        return markdown, []

    allowed = {_normalize_url_for_match(u) for u in source_urls if u}
    stripped: list[str] = []

    def _replace(match: re.Match) -> str:
        label = match.group(1)
        url = match.group(2)
        if _normalize_url_for_match(url) in allowed:
            return match.group(0)  # keep as-is
        stripped.append(url)
        return label  # drop the link, keep the label

    cleaned = _MARKDOWN_LINK_RE.sub(_replace, markdown)
    return cleaned, stripped


# Adaptive per-tier content cap for the synthesis prompt. Tier 1
# (authoritative docs, official sources, academic) gets the most room
# because we paid the most to fetch it. Tier 3 gets the least so junk
# forums can't crowd out the high-signal material.
_TIER_CONTENT_CAP = {1: 8000, 2: 3000, 3: 1000}


def _truncate_for_tier(content: str, tier: int) -> str:
    """Cap a source's content length based on its authority tier."""
    if not content:
        return ""
    cap = _TIER_CONTENT_CAP.get(tier, 1000)
    if len(content) <= cap:
        return content
    return content[:cap].rstrip() + " ..."


def _deduplicate_results(results: list[dict]) -> list[dict]:
    """Remove duplicate results by URL and near-duplicate content."""
    # Pass 1: URL dedup
    seen_urls: set[str] = set()
    url_deduped: list[dict] = []
    for r in results:
        url = r.get("url", "").strip().rstrip("/")
        if not url:
            url_deduped.append(r)
            continue
        norm_url = url.lower().replace("https://", "").replace("http://", "").lstrip("www.")
        if norm_url in seen_urls:
            continue
        seen_urls.add(norm_url)
        url_deduped.append(r)

    # Pass 2: Content near-duplicate detection
    def _normalize_text(text: str) -> str:
        return re.sub(r"\s+", " ", text.lower().strip())[:300]

    final: list[dict] = []
    seen_content: list[str] = []
    for r in url_deduped:
        norm = _normalize_text(r.get("content", ""))
        if len(norm) < 20:
            final.append(r)
            continue
        is_dup = False
        for existing in seen_content:
            shorter, longer = (norm, existing) if len(norm) <= len(existing) else (existing, norm)
            if shorter in longer:
                is_dup = True
                break
            words_a = set(norm.split())
            words_b = set(existing.split())
            if words_a and words_b:
                overlap = len(words_a & words_b) / len(words_a | words_b)
                if overlap > 0.8:
                    is_dup = True
                    break
        if not is_dup:
            seen_content.append(norm)
            final.append(r)

    return final


# ---------------------------------------------------------------------------
# Two-pass critique
# ---------------------------------------------------------------------------

_CRITIQUE_SYSTEM = (
    "You are a rigorous fact-checking critic. You will be given a research draft "
    "and the source material that was used to write it. Your job is to:\n"
    "1. Check every major claim against the actual source text provided\n"
    "2. Flag claims where the draft states something the sources don't actually say "
    "(this is hallucination, even if the claim might be true from general knowledge)\n"
    "3. Flag claims where a citation [Source](url) exists but the cited source "
    "doesn't contain the specific fact being attributed to it\n"
    "4. Identify important topics the sources covered that the draft left out\n"
    "5. Check comparison tables for unsourced data (cells filled from general knowledge)\n"
    "You do NOT rewrite the draft. Return only a JSON report."
)


async def _critique_draft(
    client: httpx.AsyncClient,
    topic: str,
    draft: str,
    sources_text: str,
) -> list[dict]:
    """Run a critique pass over the synthesized draft.

    Returns a list of claim dicts:
        [{"text": str, "status": "supported"|"unsupported"|"missing", "note": str}, ...]

    Each claim has a status:
      - supported: the source material clearly backs the claim
      - unsupported: the claim isn't justified by the sources (likely hallucination)
      - missing: an important point about the topic that the draft omitted

    Returns ``[]`` if the LLM call or JSON parse fails — the caller treats
    that as "no critique available" and skips the Confidence Notes section.
    """
    user_msg = (
        f'Topic: "{topic}"\n\n'
        f"## Draft\n{draft[:8000]}\n\n"
        f"## Sources used\n{sources_text[:12000]}\n\n"
        f"Return ONLY a JSON object of the form:\n"
        f'{{"claims": [{{"text": "<claim>", "status": "supported|unsupported|missing", "note": "<short reason>"}}]}}\n\n'
        f"Rules:\n"
        f"- Up to 10 claims total.\n"
        f"- Prefer the most important / load-bearing claims, not trivia.\n"
        f"- Specifically check: are comparison table cells actually supported by sources?\n"
        f"- Specifically check: does each [Source](url) citation match what that source actually says?\n"
        f"- For 'unsupported' claims, the note should explain what's missing from the sources.\n"
        f"- For 'missing' claims, the note should explain why it matters and which source covered it.\n"
        f"- Output ONLY the JSON object, no markdown fences, no commentary."
    )
    try:
        raw = await _chat(
            client,
            system_msg=_CRITIQUE_SYSTEM,
            user_msg=user_msg,
            max_tokens=3000,
            temperature=0.1,
        )
    except Exception as exc:
        logger.warning("Critique pass failed: %s", exc)
        return []

    # Tolerant JSON parsing — strip optional markdown fence
    text = raw.strip()
    if text.startswith("```"):
        parts = text.split("\n", 1)
        if len(parts) == 2:
            text = parts[1]
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()
    # Find the outermost JSON object
    match = re.search(r"\{[\s\S]*\}", text)
    if not match:
        logger.warning("Critique pass returned no JSON object")
        return []
    try:
        obj = json.loads(match.group(0))
    except json.JSONDecodeError as exc:
        logger.warning("Critique JSON parse failed: %s", exc)
        return []

    raw_claims = obj.get("claims") or []
    if not isinstance(raw_claims, list):
        return []

    claims: list[dict] = []
    for c in raw_claims:
        if not isinstance(c, dict):
            continue
        text_v = (c.get("text") or "").strip()
        status_v = (c.get("status") or "").strip().lower()
        note_v = (c.get("note") or "").strip()
        if not text_v:
            continue
        if status_v not in ("supported", "unsupported", "missing"):
            status_v = "unsupported"
        claims.append({"text": text_v, "status": status_v, "note": note_v})
    return claims


def _render_confidence_notes(claims: list[dict]) -> str:
    """Render critique claims as an appended ## Confidence Notes section."""
    if not claims:
        return ""
    supported = [c for c in claims if c["status"] == "supported"]
    unsupported = [c for c in claims if c["status"] == "unsupported"]
    missing = [c for c in claims if c["status"] == "missing"]

    lines = ["", "", "## Confidence Notes", ""]
    lines.append(
        f"Critique pass: **{len(supported)} supported**, "
        f"**{len(unsupported)} unsupported**, "
        f"**{len(missing)} missing** claim(s)."
    )
    if unsupported:
        lines.append("")
        lines.append("**Claims the sources don't fully support:**")
        for c in unsupported:
            note = f" — _{c['note']}_" if c["note"] else ""
            lines.append(f"- {c['text']}{note}")
    if missing:
        lines.append("")
        lines.append("**Topics the sources cover that the draft omitted:**")
        for c in missing:
            note = f" — _{c['note']}_" if c["note"] else ""
            lines.append(f"- {c['text']}{note}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Per-source extraction pre-pass
# ---------------------------------------------------------------------------

# Sources shorter than this aren't worth running through extraction; they're
# already a one-paragraph snippet from Serper/Tavily.
_EXTRACTION_MIN_CHARS = 1500
# Cap on how many sources we'll extract from in a single research run, to
# bound LLM cost. Tier-1 sources beyond this fall through to raw inclusion.
_EXTRACTION_MAX_SOURCES = 6


_FACT_EXTRACTION_SYSTEM = (
    "You extract concrete factual claims from a single source. "
    "Return a bulleted list — one claim per line, prefixed with `- `. "
    "Each bullet must be specific (numbers, version IDs, dates, named "
    "features) and self-contained. Use the exact wording from the source "
    "where possible. No prose, no headers, no commentary — bullets only."
)


async def _extract_facts_from_source(
    client: httpx.AsyncClient,
    topic: str,
    source: dict,
) -> str | None:
    """Run a cheap LLM extraction over one source's content.

    Returns a bullet list of facts as a string, or ``None`` if extraction
    failed (in which case the caller should fall back to the raw content).
    """
    content = source.get("content") or ""
    if len(content) < _EXTRACTION_MIN_CHARS:
        return None

    title = source.get("title") or "(untitled)"
    url = source.get("url") or "(no url)"
    # Cap input to keep the cheap-call budget in check.
    snippet = content[:8000]
    user_msg = (
        f'Topic of interest: "{topic}"\n\n'
        f"Source: {title}\nURL: {url}\n\n"
        f"Source content:\n{snippet}\n\n"
        f"Extract every factual claim from this source that is relevant "
        f"to the topic. Up to 12 bullets."
    )
    try:
        return await _chat(
            client,
            system_msg=_FACT_EXTRACTION_SYSTEM,
            user_msg=user_msg,
            max_tokens=600,
            temperature=0.1,
        )
    except Exception as exc:
        logger.warning("Fact extraction failed for %s: %s", url, exc)
        return None


async def _extract_facts_for_tier1_sources(
    client: httpx.AsyncClient,
    topic: str,
    results: list[dict],
) -> int:
    """Run extraction in parallel over the top Tier-1 sources.

    Mutates *results* in place: each extracted source gets its ``content``
    replaced by the bullet list and its dict tagged with
    ``extracted=True``. Returns the number of sources successfully
    extracted.
    """
    targets = [
        (i, r)
        for i, r in enumerate(results)
        if r.get("tier") == 1 and len(r.get("content") or "") >= _EXTRACTION_MIN_CHARS
    ][:_EXTRACTION_MAX_SOURCES]

    if not targets:
        return 0

    coros = [_extract_facts_from_source(client, topic, r) for _, r in targets]
    extracted_results = await asyncio.gather(*coros, return_exceptions=True)

    success = 0
    for (idx, source), result in zip(targets, extracted_results):
        if isinstance(result, Exception) or not result:
            continue
        result_text = result.strip()
        if not result_text:
            continue
        # Replace the raw blob with the bullet extraction; mark it so the
        # formatter can label it visibly in the prompt.
        results[idx] = {
            **source,
            "content": result_text,
            "extracted": True,
        }
        success += 1

    if success:
        logger.info(
            "Per-source extraction: %d/%d Tier-1 sources distilled",
            success, len(targets),
        )
    return success


def _format_sources_for_prompt(results: list[dict]) -> str:
    """Format search results with tier labels for the synthesis prompt.

    Each source's content is truncated according to its tier (8000 chars
    for Tier 1, 3000 for Tier 2, 1000 for Tier 3) so the expensive Tier-1
    deep-reads keep most of their material while Tier-3 forum noise can't
    crowd them out.
    """
    sections = []
    for r in results:
        content = r.get("content") or ""
        if not content:
            continue
        tier = r.get("tier", 3)
        label = _tier_label(tier)
        capped = _truncate_for_tier(content, tier)
        marker = " [EXTRACTED FACTS]" if r.get("extracted") else ""
        sections.append(
            f"[{label}]{marker} **{r['title']}** ({r['url']})\n{capped}"
        )
    return "\n\n".join(sections)


# --- Synthesis --------------------------------------------------------------

async def _synthesize(
    client: httpx.AsyncClient, topic: str, all_results: list[dict]
) -> tuple[str, list[dict]]:
    """Run the final synthesis step to produce a structured research document.

    Returns ``(article_markdown, critique_claims)``.

    Reads ``kb_settings.synthesis_provider`` / ``synthesis_model`` via the
    ``_current_kb`` ContextVar (set by ``run_research``) and passes them
    through to ``llm_chat``. NULL settings fall back to the global
    ``LLM_PROVIDER`` env var. No hard-coded model choice — the user picks
    per KB through the admin UI.

    After the draft, runs a critique pass that returns structured JSON
    about which claims are supported / unsupported / missing. The critique
    is appended to the article as a ``## Confidence Notes`` section AND
    returned to the caller so it can be persisted to ``article_claims``.
    """
    # Cheap parallel extraction over the top Tier-1 sources. Replaces raw
    # blobs with verbatim bullet facts so the synthesis pass consumes
    # signal-dense input rather than rambling page content.
    try:
        await _extract_facts_for_tier1_sources(client, topic, all_results)
    except Exception as exc:
        logger.warning("Per-source extraction pass failed: %s", exc)

    sources_text = _format_sources_for_prompt(all_results)

    # Per-KB synthesis provider/model + persona lookup. All three come
    # from kb_settings; NULL values fall back to the global defaults.
    synth_provider: str | None = None
    synth_model: str | None = None
    persona: str | None = None
    kb_name = _current_kb.get()
    if kb_name:
        try:
            kb_cfg = await db.get_kb_settings(kb_name)
            if kb_cfg:
                synth_provider = kb_cfg.get("synthesis_provider") or None
                synth_model = kb_cfg.get("synthesis_model") or None
                persona = kb_cfg.get("persona") or None
        except Exception as exc:
            logger.warning("Failed to load kb_settings for %s: %s", kb_name, exc)

    # Prepend the per-KB persona (if any) to the synthesis system prompt.
    # Personas like "You are a senior security engineer writing for a SOC
    # team" let different KBs synthesize in different voices without
    # touching the global SYNTHESIS_SYSTEM_PROMPT.
    effective_system_prompt = SYNTHESIS_SYSTEM_PROMPT
    if persona:
        effective_system_prompt = f"{persona.strip()}\n\n{SYNTHESIS_SYSTEM_PROMPT}"

    # Detect topic type and get adaptive template
    from app.topic_classifier import classify_topic, get_article_template
    topic_type = classify_topic(topic, all_results)
    article_template = get_article_template(topic_type)
    logger.info("Topic classified as '%s' for synthesis", topic_type)

    synthesis_prompt = f"""Create a well-structured research document on the following topic.

Topic: {topic}
Topic Type: {topic_type}

You have {len(all_results)} search results from multiple rounds of agentic research (broad search, sub-topic deep dives, and verification searches). Sources are labeled by authority tier:
- Tier 1 (Authoritative): official docs, .gov, academic, major tech blogs. PRIORITIZE these.
- Tier 2 (Reputable): Stack Overflow, known blogs, reputable news. Use as supporting evidence.
- Tier 3 (General): other blogs, forums. Use cautiously, cross-reference when possible.

CRITICAL RULES:
- Only state facts that come from the provided sources. Do NOT fill in gaps with general knowledge or your training data.
- If a source is clearly about a different topic (wrong subject, spam, unrelated content), IGNORE it completely.
- If an obvious aspect of this topic isn't covered by any source, call it out in Limitations. Do NOT guess.
- Focus on what makes this topic interesting and useful, not exhaustive raw data.
- If you want to include a comparison table, every cell must be citable. Leave cells blank or write "not available" rather than guessing.
- Complete every section fully. If approaching token limits, close the current section cleanly.

TITLE: Write a clear, specific title for this article. Do NOT use the pattern "X: A Comprehensive Research Document." Use a natural title like "Townsville, Australia" or "Kubernetes RBAC Best Practices."

{article_template}

Search Results:
{sources_text}"""

    # Retry synthesis up to RESEARCH_MAX_RETRIES times on timeout
    from app.config import RESEARCH_MAX_RETRIES, RESEARCH_RETRY_DELAY
    draft: str | None = None
    for attempt in range(1, RESEARCH_MAX_RETRIES + 2):
        try:
            draft = await _chat(
                client,
                system_msg=effective_system_prompt,
                user_msg=synthesis_prompt,
                max_tokens=16000,
                temperature=0.2,
                model=synth_model,
                provider=synth_provider,
            )
            break
        except (httpx.TimeoutException, httpx.ReadTimeout):
            if attempt <= RESEARCH_MAX_RETRIES:
                logger.warning("Synthesis timeout (attempt %d/%d), retrying in %ds...",
                               attempt, RESEARCH_MAX_RETRIES + 1, RESEARCH_RETRY_DELAY)
                await asyncio.sleep(RESEARCH_RETRY_DELAY)
            else:
                raise

    if draft is None:
        # Should never reach here — the retry loop either returns a draft
        # or raises — but appease the type checker.
        raise RuntimeError("Synthesis returned no draft")

    # Self-citation lint — strip any [label](url) where the URL wasn't in
    # the source set the model was given. Hallucinated citations would
    # otherwise leak through into the published article.
    source_urls = [r.get("url", "") for r in all_results if r.get("url")]
    cleaned, stripped = _lint_citations(draft, source_urls)
    if stripped:
        logger.warning(
            "Synthesis: stripped %d hallucinated citation(s) — first few: %s",
            len(stripped), stripped[:3],
        )

    # Critique pass — verify the draft against the sources and append a
    # Confidence Notes section. Failures are logged and ignored so a
    # critique-pass error never blocks article publishing.
    critique_claims: list[dict] = []
    try:
        critique_claims = await _critique_draft(
            client, topic, cleaned, sources_text,
        )
    except Exception as exc:
        logger.warning("Critique pass crashed: %s", exc)

    if critique_claims:
        notes = _render_confidence_notes(critique_claims)
        if notes:
            cleaned = cleaned.rstrip() + notes

    return cleaned, critique_claims


# --- Query refinement -------------------------------------------------------

async def refine_query(topic: str) -> str:
    """Use LLM to fix spelling errors and improve search query.

    Returns the refined query, or the original topic if refinement fails.
    """
    has_llm = (LLM_PROVIDER == "bedrock") or MINIMAX_API_KEY
    if not has_llm:
        return topic

    try:
        result = await llm_chat(
            system_msg=(
                "You are a search query optimizer. Fix any spelling errors, expand abbreviations, "
                "and improve the query for web search. Return ONLY the corrected query text, nothing else. "
                "Do not add quotes or extra formatting. If the query is already correct, return it unchanged."
            ),
            user_msg=topic,
            max_tokens=100,
            temperature=0.0,
        )
        refined = result.strip().strip('"').strip("'")
        if refined and 3 <= len(refined) <= len(topic) * 3:
            if refined.lower() != topic.lower():
                logger.info("Query refined: '%s' -> '%s'", topic, refined)
            return refined
    except Exception as exc:
        logger.warning("Query refinement failed: %s", exc)

    return topic


# --- Main pipeline ----------------------------------------------------------

async def run_research(topic: str, job_id: int, kb_name: str = "personal") -> None:
    """Execute the full 3-round research pipeline for a topic.

    Updates the SQLite job record at each stage. On completion, writes the
    research output to disk and stores the synthesized content in the DB.

    ``kb_name`` is used purely for per-KB Serper budget accounting; it does
    not affect where the article is later merged (that's the caller's job).
    """
    _job_token = _current_job_id.set(job_id)
    _kb_token = _current_kb.set(kb_name)
    try:
        return await _run_research_impl(topic, job_id)
    finally:
        _current_job_id.reset(_job_token)
        _current_kb.reset(_kb_token)


async def _run_research_impl(topic: str, job_id: int) -> None:
    await db.update_job(job_id, status="searching_round_1")

    if not SERPER_API_KEY:
        await db.update_job(
            job_id, status="error",
            error="No search API key configured (SERPER_API_KEY required)",
        )
        return

    if LLM_PROVIDER == "minimax" and not MINIMAX_API_KEY:
        await db.update_job(job_id, status="error", error="MINIMAX_API_KEY not set")
        return

    # Refine query: fix spelling, expand abbreviations
    search_query = await refine_query(topic)

    all_results: list[dict] = []

    # ── Round 1: Broad search across ALL registered providers ────────────
    # Serper, Tavily, arXiv, HN, Wikipedia, etc. run in parallel.
    # Per-provider failures are non-fatal; the rest still contribute.
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            round1_results = await _round1_search_all_providers(
                client, search_query, per_provider=5,
            )
            all_results.extend(round1_results)

        logger.info(
            "Research [%d] round 1: %d results for '%s' (query: '%s')",
            job_id, len(all_results), topic, search_query,
        )
    except httpx.HTTPStatusError as exc:
        await db.update_job(
            job_id, status="error",
            error=f"Search API HTTP {exc.response.status_code}: {exc.response.text[:200]}",
        )
        return
    except httpx.TimeoutException:
        await db.update_job(
            job_id, status="error", error="Search API request timed out (round 1)",
        )
        return
    except Exception as exc:
        await db.update_job(job_id, status="error", error=f"Search failed (round 1): {exc}")
        return

    if not all_results:
        await db.update_job(job_id, status="no_results", sources_count=0)
        return

    # Score and save round 1 sources
    for r in all_results:
        r["tier"] = _score_source_tier(r.get("url", ""))
    await db.save_sources(job_id, all_results, round_num=1)

    # ── Round 2: Sub-topic queries via Minimax ─────────────────────────────
    await db.update_job(job_id, status="searching_round_2")

    round1_summaries = "\n".join(
        f"- {r['title']}: {r['content'][:150]}"
        for r in all_results
        if r.get("content")
    )

    round2_results: list[dict] = []
    sub_questions: list[str] = []
    try:
        async with httpx.AsyncClient(timeout=60) as client:
            sub_questions = await _generate_sub_questions(client, topic, round1_summaries)
            logger.info(
                "Research [%d] round 2: generated %d sub-questions",
                job_id, len(sub_questions),
            )
    except Exception as exc:
        logger.warning("Research [%d] sub-question generation failed: %s", job_id, exc)

    if sub_questions:
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                for sq in sub_questions:
                    try:
                        sq_results = await _search_serper(client, sq, num=4)
                        round2_results.extend(sq_results)
                    except Exception as exc:
                        logger.warning(
                            "Research [%d] sub-search failed for '%s': %s",
                            job_id, sq[:50], exc,
                        )
        except Exception as exc:
            logger.warning("Research [%d] round 2 search phase failed: %s", job_id, exc)

    for r in round2_results:
        r["tier"] = _score_source_tier(r.get("url", ""))
    all_results.extend(round2_results)
    await db.save_sources(job_id, round2_results, round_num=2)

    # ── Deduplication and scoring ──────────────────────────────────────────
    all_results = _deduplicate_results(all_results)
    for r in all_results:
        if "tier" not in r:
            r["tier"] = _score_source_tier(r.get("url", ""))
    all_results.sort(key=lambda r: r["tier"])

    logger.info("Research [%d] after dedup: %d unique results", job_id, len(all_results))

    # ── Round 3: Verification searches ─────────────────────────────────────
    await db.update_job(job_id, status="searching_round_3")

    round3_results: list[dict] = []
    verification_queries: list[str] = []
    try:
        async with httpx.AsyncClient(timeout=60) as client:
            top_sources = _format_sources_for_prompt(all_results[:15])
            verification_queries = await _generate_verification_queries(
                client, topic, top_sources,
            )
            logger.info(
                "Research [%d] round 3: %d verification queries",
                job_id, len(verification_queries),
            )
    except Exception as exc:
        logger.warning("Research [%d] claim extraction failed: %s", job_id, exc)

    if verification_queries:
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                for vq in verification_queries:
                    try:
                        vq_results = await _search_serper(client, vq, num=3)
                        round3_results.extend(vq_results)
                    except Exception as exc:
                        logger.warning(
                            "Research [%d] verification search failed for '%s': %s",
                            job_id, vq[:50], exc,
                        )
        except Exception as exc:
            logger.warning("Research [%d] round 3 search phase failed: %s", job_id, exc)

    for r in round3_results:
        r["tier"] = _score_source_tier(r.get("url", ""))
    all_results.extend(round3_results)
    await db.save_sources(job_id, round3_results, round_num=3)

    # Re-deduplicate after round 3
    all_results = _deduplicate_results(all_results)
    for r in all_results:
        if "tier" not in r:
            r["tier"] = _score_source_tier(r.get("url", ""))
    all_results.sort(key=lambda r: r["tier"])

    # ── Round 4a: Download PDFs/ePubs found in search results ─────────────
    try:
        from app.browser import find_document_urls, download_documents

        doc_urls = find_document_urls(all_results)
        if doc_urls:
            await db.update_job(job_id, status="downloading_docs")
            docs = await download_documents(doc_urls[:3])  # max 3 documents
            for doc in docs:
                # Keep up to 8000 chars from docs; the formatter will
                # further cap based on the source's tier.
                all_results.append({
                    "title": doc["title"],
                    "content": doc["content"][:8000],
                    "url": doc["url"],
                    "tier": _score_source_tier(doc["url"]),
                    "source": doc.get("source", "downloaded"),
                })
            logger.info(
                "Research [%d] documents: downloaded %d/%d",
                job_id, len(docs), len(doc_urls),
            )
            await db.save_sources(job_id, [
                {"title": d["title"], "content": d["content"][:500], "url": d["url"]}
                for d in docs
            ], round_num=4)
    except Exception as exc:
        logger.warning("Research [%d] document download failed: %s", job_id, exc)

    # ── Round 4b: Deep page reading (agent-browser + httpx fallback) ─────
    # Read full page content from the top Tier 1/2 URLs found in search
    await db.update_job(job_id, status="reading_pages")
    try:
        from app.browser import read_pages_smart

        # Pick top URLs from Tier 1 and Tier 2 sources
        # Tier values are integers (1, 2, 3) from _score_source_tier.
        urls_to_read = []
        seen_urls = set()
        for r in all_results:
            url = r.get("url", "")
            if (
                url
                and url.startswith("http")
                and r.get("tier") in (1, 2)
                and url not in seen_urls
            ):
                urls_to_read.append(url)
                seen_urls.add(url)
            if len(urls_to_read) >= 5:
                break

        if urls_to_read:
            pages = await read_pages_smart(urls_to_read, max_concurrent=3)
            for page in pages:
                # Keep up to 8000 chars from deep-reads; the formatter
                # will cap based on the resolved source tier.
                all_results.append({
                    "title": page["title"],
                    "content": page["content"][:8000],
                    "url": page["url"],
                    "tier": _score_source_tier(page["url"]),
                    "source": page.get("source", "jina_reader"),
                })
            logger.info(
                "Research [%d] deep reading: %d/%d pages read",
                job_id, len(pages), len(urls_to_read),
            )
            await db.save_sources(job_id, [
                {"title": p["title"], "content": p["content"][:500], "url": p["url"]}
                for p in pages
            ], round_num=4)
        else:
            logger.info("Research [%d] no Tier 1/2 URLs to read", job_id)
    except Exception as exc:
        logger.warning("Research [%d] deep page reading failed: %s", job_id, exc)

    # ── Synthesis ──────────────────────────────────────────────────────────
    await db.update_job(job_id, status="synthesizing", sources_count=len(all_results))

    try:
        async with httpx.AsyncClient(timeout=240) as client:
            content, critique_claims = await _synthesize(client, topic, all_results)
    except httpx.HTTPStatusError as exc:
        await db.update_job(
            job_id, status="error",
            error=f"Minimax API HTTP {exc.response.status_code}: {exc.response.text[:200]}",
        )
        return
    except httpx.TimeoutException:
        await db.update_job(
            job_id, status="error",
            error="Minimax API request timed out during synthesis",
        )
        return
    except Exception as exc:
        await db.update_job(job_id, status="error", error=f"Synthesis failed: {exc}")
        return

    # ── Write output ───────────────────────────────────────────────────────
    await db.update_job(job_id, status="writing")

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    safe_topic = "".join(c if c.isalnum() or c in " -" else "_" for c in topic)[:80]
    filename = f"research-{today}-{safe_topic.replace(' ', '-')}.md"

    try:
        from app import storage
        from app.config import RESEARCH_KB
        report = f"# Research: {topic}\n\n*{today}*\n\n{content}\n"
        storage.write_text(RESEARCH_KB, filename, report)
    except Exception as exc:
        await db.update_job(job_id, status="error", error=f"Failed to write output: {exc}")
        return

    await db.update_job(
        job_id,
        status="complete",
        completed_at=datetime.now(timezone.utc).isoformat(),
        sources_count=len(all_results),
        word_count=len(content.split()),
        content=content,
        claims_json=(json.dumps(critique_claims) if critique_claims else None),
    )
    logger.info(
        "Research [%d] complete: %d sources, %d words, %d critique claims",
        job_id, len(all_results), len(content.split()), len(critique_claims),
    )


# --- Two-phase pipeline (source review) ------------------------------------

async def run_research_collect(topic: str, job_id: int, kb_name: str = "personal") -> None:
    """Source-collection phase of the two-step research flow.

    Same as ``run_research`` up to synthesis, but stops with status
    ``awaiting_review`` so the user can select/deselect sources before
    triggering synthesis (see ``run_research_synthesize``).
    """
    _job_token = _current_job_id.set(job_id)
    _kb_token = _current_kb.set(kb_name)
    try:
        return await _run_research_collect_impl(topic, job_id)
    finally:
        _current_job_id.reset(_job_token)
        _current_kb.reset(_kb_token)


async def _run_research_collect_impl(topic: str, job_id: int) -> None:
    await db.update_job(job_id, status="searching_round_1")

    if not SERPER_API_KEY:
        await db.update_job(
            job_id, status="error",
            error="No search API key configured (SERPER_API_KEY required)",
        )
        return

    if LLM_PROVIDER == "minimax" and not MINIMAX_API_KEY:
        await db.update_job(job_id, status="error", error="MINIMAX_API_KEY not set")
        return

    search_query = await refine_query(topic)
    all_results: list[dict] = []

    # ── Round 1: Broad search across ALL registered providers ────────────
    # Parallel multi-provider search (same path as run_research).
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            round1_results = await _round1_search_all_providers(
                client, search_query, per_provider=5,
            )
            all_results.extend(round1_results)
        logger.info(
            "Research [%d] round 1: %d results for '%s'",
            job_id, len(all_results), topic,
        )
    except httpx.HTTPStatusError as exc:
        await db.update_job(
            job_id, status="error",
            error=f"Search API HTTP {exc.response.status_code}: {exc.response.text[:200]}",
        )
        return
    except httpx.TimeoutException:
        await db.update_job(job_id, status="error", error="Search API request timed out (round 1)")
        return
    except Exception as exc:
        await db.update_job(job_id, status="error", error=f"Search failed (round 1): {exc}")
        return

    if not all_results:
        await db.update_job(job_id, status="no_results", sources_count=0)
        return

    for r in all_results:
        r["tier"] = _score_source_tier(r.get("url", ""))
    await db.save_sources(job_id, all_results, round_num=1)

    # ── Round 2: Sub-topic queries ─────────────────────────────────────────
    await db.update_job(job_id, status="searching_round_2")
    round1_summaries = "\n".join(
        f"- {r['title']}: {r['content'][:150]}" for r in all_results if r.get("content")
    )
    round2_results: list[dict] = []
    sub_questions: list[str] = []
    try:
        async with httpx.AsyncClient(timeout=60) as client:
            sub_questions = await _generate_sub_questions(client, topic, round1_summaries)
    except Exception as exc:
        logger.warning("Research [%d] sub-question generation failed: %s", job_id, exc)

    if sub_questions:
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                for sq in sub_questions:
                    try:
                        sq_results = await _search_serper(client, sq, num=4)
                        round2_results.extend(sq_results)
                    except Exception as exc:
                        logger.warning("Research [%d] sub-search failed: %s", job_id, exc)
        except Exception as exc:
            logger.warning("Research [%d] round 2 failed: %s", job_id, exc)

    for r in round2_results:
        r["tier"] = _score_source_tier(r.get("url", ""))
    all_results.extend(round2_results)
    await db.save_sources(job_id, round2_results, round_num=2)

    all_results = _deduplicate_results(all_results)
    for r in all_results:
        if "tier" not in r:
            r["tier"] = _score_source_tier(r.get("url", ""))
    all_results.sort(key=lambda r: r["tier"])

    # ── Round 3: Verification searches ─────────────────────────────────────
    await db.update_job(job_id, status="searching_round_3")
    round3_results: list[dict] = []
    try:
        async with httpx.AsyncClient(timeout=60) as client:
            top_sources = _format_sources_for_prompt(all_results[:15])
            verification_queries = await _generate_verification_queries(client, topic, top_sources)
    except Exception as exc:
        logger.warning("Research [%d] claim extraction failed: %s", job_id, exc)
        verification_queries = []

    if verification_queries:
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                for vq in verification_queries:
                    try:
                        vq_results = await _search_serper(client, vq, num=3)
                        round3_results.extend(vq_results)
                    except Exception as exc:
                        logger.warning("Research [%d] verification search failed: %s", job_id, exc)
        except Exception as exc:
            logger.warning("Research [%d] round 3 failed: %s", job_id, exc)

    for r in round3_results:
        r["tier"] = _score_source_tier(r.get("url", ""))
    all_results.extend(round3_results)
    await db.save_sources(job_id, round3_results, round_num=3)

    all_results = _deduplicate_results(all_results)
    for r in all_results:
        if "tier" not in r:
            r["tier"] = _score_source_tier(r.get("url", ""))
    all_results.sort(key=lambda r: r["tier"])

    # ── Round 4a: Download documents ───────────────────────────────────────
    try:
        from app.browser import find_document_urls, download_documents
        doc_urls = find_document_urls(all_results)
        if doc_urls:
            await db.update_job(job_id, status="downloading_docs")
            docs = await download_documents(doc_urls[:3])
            for doc in docs:
                all_results.append({
                    "title": doc["title"],
                    "content": doc["content"][:5000],
                    "url": doc["url"],
                    "tier": _score_source_tier(doc["url"]),
                })
            await db.save_sources(job_id, [
                {"title": d["title"], "content": d["content"][:500], "url": d["url"]}
                for d in docs
            ], round_num=4)
    except Exception as exc:
        logger.warning("Research [%d] document download failed: %s", job_id, exc)

    # ── Round 4b: Deep page reading ────────────────────────────────────────
    await db.update_job(job_id, status="reading_pages")
    try:
        from app.browser import read_pages_smart
        urls_to_read = []
        seen_urls = set()
        for r in all_results:
            url = r.get("url", "")
            if url and url.startswith("http") and r.get("tier") in ("tier_1", "tier_2") and url not in seen_urls:
                urls_to_read.append(url)
                seen_urls.add(url)
            if len(urls_to_read) >= 5:
                break
        if urls_to_read:
            pages = await read_pages_smart(urls_to_read, max_concurrent=3)
            for page in pages:
                all_results.append({
                    "title": page["title"],
                    "content": page["content"][:3000],
                    "url": page["url"],
                    "tier": _score_source_tier(page["url"]),
                })
            await db.save_sources(job_id, [
                {"title": p["title"], "content": p["content"][:500], "url": p["url"]}
                for p in pages
            ], round_num=4)
    except Exception as exc:
        logger.warning("Research [%d] deep page reading failed: %s", job_id, exc)

    # ── Pause for source review ────────────────────────────────────────────
    await db.update_job(
        job_id,
        status="awaiting_review",
        sources_count=len(all_results),
    )
    logger.info(
        "Research [%d] sources collected: %d results, awaiting review",
        job_id, len(all_results),
    )


async def run_research_synthesize(topic: str, job_id: int) -> None:
    """Synthesize an article from user-selected sources only.

    Reads selected sources from DB and runs synthesis + write steps.
    """
    selected_sources = await db.get_selected_sources(job_id)
    if not selected_sources:
        await db.update_job(job_id, status="error", error="No sources selected for synthesis")
        return

    # Convert DB rows to the format expected by _synthesize
    all_results = [
        {
            "title": s["title"],
            "content": s["content"],
            "url": s["url"],
            "tier": s.get("tier", 3),
        }
        for s in selected_sources
    ]

    await db.update_job(job_id, status="synthesizing", sources_count=len(all_results))

    try:
        async with httpx.AsyncClient(timeout=240) as client:
            content, critique_claims = await _synthesize(client, topic, all_results)
    except httpx.HTTPStatusError as exc:
        await db.update_job(
            job_id, status="error",
            error=f"LLM API HTTP {exc.response.status_code}: {exc.response.text[:200]}",
        )
        return
    except httpx.TimeoutException:
        await db.update_job(job_id, status="error", error="LLM API timed out during synthesis")
        return
    except Exception as exc:
        await db.update_job(job_id, status="error", error=f"Synthesis failed: {exc}")
        return

    # ── Write output ───────────────────────────────────────────────────────
    await db.update_job(job_id, status="writing")

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    safe_topic = "".join(c if c.isalnum() or c in " -" else "_" for c in topic)[:80]
    filename = f"research-{today}-{safe_topic.replace(' ', '-')}.md"

    try:
        from app import storage
        from app.config import RESEARCH_KB
        report = f"# Research: {topic}\n\n*{today}*\n\n{content}\n"
        storage.write_text(RESEARCH_KB, filename, report)
    except Exception as exc:
        await db.update_job(job_id, status="error", error=f"Failed to write output: {exc}")
        return

    await db.update_job(
        job_id,
        status="complete",
        completed_at=datetime.now(timezone.utc).isoformat(),
        sources_count=len(all_results),
        word_count=len(content.split()),
        content=content,
        claims_json=(json.dumps(critique_claims) if critique_claims else None),
    )
    logger.info(
        "Research [%d] synthesis complete: %d selected sources, %d words, %d critique claims",
        job_id, len(all_results), len(content.split()), len(critique_claims),
    )
